import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const mainFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by RyzeCanvas AI Orchestration Engine",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mainFont.className}>
        {children}
      </body>
    </html>
  );
}
