import type { ReactNode } from "react";
import "../styles/globals.css";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" className="dark bg-backgroundDark text-primary">
      <head />
      <body className="font-body min-h-screen flex flex-col">
        {children}
      </body>
    </html>
  );
}