import type { Metadata } from "next";
import { Inter,_sans-serif, Roboto,_sans-serif } from "next/font/google";
import "./globals.css";

const headingFont = Inter,_sans-serif({ subsets: ["latin"], variable: "--font-heading" });
const bodyFont = Roboto,_sans-serif({ subsets: ["latin"], variable: "--font-body" });

export const metadata: Metadata = {
  title: "e-commerce-page",
  description: "Generated by RyzeCanvas AI Orchestration Engine",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${headingFont.variable} ${bodyFont.variable}`}>
      <body className={bodyFont.className}>
        {children}
      </body>
    </html>
  );
}
