"""
Component Library Schema for RyzeCanvas AI Agent.
Defines the strict set of allowed UI components and their structure.
"""
from typing import List, Optional, Dict, Any, Literal
from pydantic import BaseModel, Field


# Allowed component types - the ONLY components the AI can use
ALLOWED_COMPONENTS = [
    'Button',
    'Card',
    'Input',
    'Table',
    'Navbar',
    'Sidebar',
    'Chart',
    'Text',
    'Image',
    'Container',
    'Form',
    'Select',
    'Checkbox',
    'Radio'
]

ComponentType = Literal[
    'Button', 'Card', 'Input', 'Table', 'Navbar', 
    'Sidebar', 'Chart', 'Text', 'Image', 'Container',
    'Form', 'Select', 'Checkbox', 'Radio'
]


class Position(BaseModel):
    """Position coordinates for a component."""
    x: int = Field(..., description="X coordinate in pixels")
    y: int = Field(..., description="Y coordinate in pixels")


class ComponentNode(BaseModel):
    """
    A single UI component node in the generated plan.
    Each component must conform to the allowed component library.
    """
    id: str = Field(..., description="Unique identifier for this component (e.g., 'btn_1', 'card_2')")
    type: ComponentType = Field(..., description="Type of component from the allowed library")
    props: Dict[str, Any] = Field(
        default_factory=dict,
        description="Component-specific properties (label, placeholder, variant, etc.)"
    )
    position: Position = Field(..., description="Position on the canvas")
    styles: Optional[Dict[str, str]] = Field(
        default=None,
        description="Optional CSS-in-JS styles"
    )
    children: Optional[List['ComponentNode']] = Field(
        default=None,
        description="Nested child components (for containers)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "id": "btn_submit",
                "type": "Button",
                "props": {
                    "label": "Submit",
                    "variant": "primary",
                    "onClick": "handleSubmit"
                },
                "position": {"x": 100, "y": 200},
                "styles": {
                    "backgroundColor": "#3b82f6",
                    "color": "#ffffff",
                    "padding": "12px 24px",
                    "borderRadius": "8px"
                }
            }
        }


class LayoutConfig(BaseModel):
    """Layout configuration for the entire canvas."""
    theme: Literal['light', 'dark'] = Field(default='light', description="UI theme")
    grid: bool = Field(default=True, description="Enable grid snapping")
    gridSize: int = Field(default=20, description="Grid size in pixels")
    canvasSize: Dict[str, int] = Field(
        default={"width": 1920, "height": 1080},
        description="Canvas dimensions"
    )


class UIPlan(BaseModel):
    """
    The complete UI Plan generated by the AI Agent.
    This is the structured output that gets saved to the database.
    """
    components: List[ComponentNode] = Field(
        ...,
        description="List of all UI components in the plan"
    )
    layout: LayoutConfig = Field(
        default_factory=LayoutConfig,
        description="Canvas layout configuration"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=lambda: {
            "version": "1.0",
            "generatedBy": "RyzeCanvas AI Agent"
        },
        description="Additional metadata about the plan"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "components": [
                    {
                        "id": "navbar_1",
                        "type": "Navbar",
                        "props": {"title": "My App", "items": ["Home", "About", "Contact"]},
                        "position": {"x": 0, "y": 0}
                    },
                    {
                        "id": "card_1",
                        "type": "Card",
                        "props": {"title": "Welcome", "content": "Get started with your app"},
                        "position": {"x": 100, "y": 100}
                    },
                    {
                        "id": "btn_1",
                        "type": "Button",
                        "props": {"label": "Get Started", "variant": "primary"},
                        "position": {"x": 100, "y": 300}
                    }
                ],
                "layout": {
                    "theme": "dark",
                    "grid": True,
                    "gridSize": 20,
                    "canvasSize": {"width": 1920, "height": 1080}
                },
                "metadata": {
                    "version": "1.0",
                    "generatedBy": "RyzeCanvas AI Agent"
                }
            }
        }


# Component-specific property templates for AI guidance
COMPONENT_TEMPLATES = {
    "Button": {
        "required_props": ["label"],
        "optional_props": ["variant", "size", "onClick", "disabled", "icon"],
        "example": {
            "label": "Click Me",
            "variant": "primary",  # primary, secondary, outline, ghost
            "size": "medium",  # small, medium, large
            "onClick": "handleClick"
        }
    },
    "Card": {
        "required_props": ["title"],
        "optional_props": ["content", "footer", "image", "variant"],
        "example": {
            "title": "Card Title",
            "content": "Card description or content goes here",
            "footer": "Footer text",
            "variant": "elevated"  # flat, elevated, outlined
        }
    },
    "Input": {
        "required_props": ["placeholder"],
        "optional_props": ["type", "label", "value", "onChange", "disabled", "error"],
        "example": {
            "placeholder": "Enter text...",
            "type": "text",  # text, email, password, number, tel
            "label": "Username",
            "onChange": "handleInputChange"
        }
    },
    "Table": {
        "required_props": ["columns", "data"],
        "optional_props": ["striped", "hoverable", "bordered"],
        "example": {
            "columns": ["Name", "Email", "Role"],
            "data": [
                ["John Doe", "john@example.com", "Admin"],
                ["Jane Smith", "jane@example.com", "User"]
            ],
            "striped": True,
            "hoverable": True
        }
    },
    "Navbar": {
        "required_props": ["title"],
        "optional_props": ["items", "logo", "actions"],
        "example": {
            "title": "My Application",
            "items": ["Home", "About", "Services", "Contact"],
            "logo": "/logo.png"
        }
    },
    "Sidebar": {
        "required_props": ["items"],
        "optional_props": ["title", "collapsed", "width"],
        "example": {
            "items": [
                {"label": "Dashboard", "icon": "home", "link": "/dashboard"},
                {"label": "Projects", "icon": "folder", "link": "/projects"},
                {"label": "Settings", "icon": "settings", "link": "/settings"}
            ],
            "width": 250
        }
    },
    "Chart": {
        "required_props": ["type", "data"],
        "optional_props": ["title", "xAxis", "yAxis", "colors"],
        "example": {
            "type": "bar",  # bar, line, pie, donut, area
            "data": [
                {"label": "Jan", "value": 30},
                {"label": "Feb", "value": 45},
                {"label": "Mar", "value": 60}
            ],
            "title": "Monthly Sales",
            "xAxis": "Month",
            "yAxis": "Sales"
        }
    },
    "Text": {
        "required_props": ["content"],
        "optional_props": ["variant", "size", "weight", "color"],
        "example": {
            "content": "This is sample text",
            "variant": "paragraph",  # heading1, heading2, heading3, paragraph, caption
            "size": "medium",
            "weight": "normal"  # normal, bold, light
        }
    },
    "Form": {
        "required_props": ["fields"],
        "optional_props": ["title", "submitLabel", "onSubmit"],
        "example": {
            "title": "Contact Form",
            "fields": [
                {"name": "name", "type": "text", "label": "Name", "required": True},
                {"name": "email", "type": "email", "label": "Email", "required": True},
                {"name": "message", "type": "textarea", "label": "Message"}
            ],
            "submitLabel": "Send Message"
        }
    },
    "Select": {
        "required_props": ["options"],
        "optional_props": ["label", "placeholder", "value", "onChange", "multiple"],
        "example": {
            "label": "Choose an option",
            "placeholder": "Select...",
            "options": ["Option 1", "Option 2", "Option 3"],
            "onChange": "handleSelectChange"
        }
    },
    "Image": {
        "required_props": ["src", "alt"],
        "optional_props": ["width", "height", "rounded", "objectFit"],
        "example": {
            "src": "/placeholder.png",
            "alt": "Description",
            "width": 100,
            "height": 100,
            "rounded": True
        }
    },
    "Container": {
        "required_props": [],
        "optional_props": ["layout", "direction", "gap", "padding", "background", "children"],
        "example": {
            "layout": "flex",
            "direction": "row",
            "gap": 10,
            "padding": "20px"
        }
    },
    "Checkbox": {
        "required_props": ["label"],
        "optional_props": ["checked", "onChange", "disabled"],
        "example": {
            "label": "Agree to terms",
            "checked": False
        }
    },
    "Radio": {
        "required_props": ["name", "options"],
        "optional_props": ["label", "value", "onChange"],
        "example": {
            "name": "gender",
            "label": "Gender",
            "options": ["Male", "Female", "Other"]
        }
    }
}


def get_component_template(component_type: str) -> Optional[Dict[str, Any]]:
    """Get the template for a specific component type."""
    return COMPONENT_TEMPLATES.get(component_type)


def validate_component_type(component_type: str) -> bool:
    """Validate if a component type is allowed."""
    return component_type in ALLOWED_COMPONENTS


# System prompt template for the AI agent
SYSTEM_PROMPT = """You are a professional UI/UX Architect AI for RyzeCanvas.

Your ONLY task is to generate deterministic, structured JSON UI plans using the provided component library.

**STRICT RULES:**
1. You MUST ONLY use components from this list: {allowed_components}
2. You MUST NOT invent new component types or HTML tags
3. You MUST generate valid JSON matching the UIPlan schema
4. You MUST assign unique IDs to each component (e.g., 'btn_1', 'card_main', 'input_email')
5. You MUST position components logically on a 1920x1080 canvas
6. You MUST include all required props for each component type

**Component Library:**
{component_templates}

**Output Format:**
Return ONLY valid JSON matching this schema:
{{
  "components": [
    {{
      "id": "unique_id",
      "type": "ComponentType",
      "props": {{}},
      "position": {{"x": 0, "y": 0}},
      "styles": {{}} (optional)
    }}
  ],
  "layout": {{
    "theme": "light|dark",
    "grid": true,
    "gridSize": 20,
    "canvasSize": {{"width": 1920, "height": 1080}}
  }}
}}

**Example Input:** "Create a login screen"
**Example Output:**
{{
  "components": [
    {{
      "id": "card_login",
      "type": "Card",
      "props": {{
        "title": "Login",
        "content": "Enter your credentials"
      }},
      "position": {{"x": 760, "y": 300}}
    }},
    {{
      "id": "input_email",
      "type": "Input",
      "props": {{
        "placeholder": "Email address",
        "type": "email",
        "label": "Email"
      }},
      "position": {{"x": 760, "y": 400}}
    }},
    {{
      "id": "input_password",
      "type": "Input",
      "props": {{
        "placeholder": "Password",
        "type": "password",
        "label": "Password"
      }},
      "position": {{"x": 760, "y": 480}}
    }},
    {{
      "id": "btn_login",
      "type": "Button",
      "props": {{
        "label": "Sign In",
        "variant": "primary"
      }},
      "position": {{"x": 760, "y": 560}}
    }}
  ],
  "layout": {{
    "theme": "light",
    "grid": true,
    "gridSize": 20,
    "canvasSize": {{"width": 1920, "height": 1080}}
  }}
}}

Remember: Output ONLY valid JSON. No markdown, no explanations, just pure JSON.
"""
